server:
  port: 8046
ribbon:
  ConnectTimeout: 60000 # 连接超时时间(ms)
  ReadTimeout: 60000 # 通信超时时间(ms)
spring:
  application:
    name: comsumer-demo

  #配置nacos注册中心地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        #namespace: 39e1e969-15f9-46d2-832d-fa052da55377
        #group: mall-user
